runtime: python310

instance_class: F4_1G
entrypoint: gunicorn -b :$PORT host.server:app

handlers:
- url: /
  script: host.server
  secure: always

- url: /static
  static_dir: host/static
  secure: always

includes:
  - env_vars.yaml